export const ORG_META: Record<string, { name: string; target: number; icon: string; color: string }> = {
  ml4sci:   { name: 'ML4SCI',   target: 3, icon: 'flask',  color: '#64ffda' },
  kubeflow: { name: 'Kubeflow', target: 2, icon: 'cloud',  color: '#7eb3ff' },
  airflow:  { name: 'Airflow',  target: 1, icon: 'wind',   color: '#ff9f43' },
}

export const ORG_LINKS: Record<string, { label: string; url: string }[]> = {
  ml4sci: [
    { label: 'ML4DQM Repo',       url: 'https://github.com/ML4SCI/ML4DQM' },
    { label: 'ML4SCI Org',        url: 'https://github.com/ML4SCI' },
    { label: 'GSoC Page',         url: 'https://summerofcode.withgoogle.com/programs/2026/organizations/machine-learning-for-science-ml4sci' },
    { label: 'Good First Issues', url: 'https://github.com/search?q=org%3AML4SCI+label%3A%22good+first+issue%22&type=issues' },
    { label: 'DeepLense Repo',    url: 'https://github.com/ML4SCI/DeepLense' },
    { label: 'CERN Open Data',    url: 'https://opendata.cern.ch' },
  ],
  kubeflow: [
    { label: 'Kubeflow Pipelines', url: 'https://github.com/kubeflow/pipelines' },
    { label: 'Kubeflow Org',       url: 'https://github.com/kubeflow' },
    { label: 'Good First Issues',  url: 'https://github.com/search?q=org%3Akubeflow+label%3A%22good+first+issue%22&type=issues' },
    { label: 'Kubeflow Website',   url: 'https://www.kubeflow.org' },
    { label: 'Kubeflow Slack',     url: 'https://kubeflow.slack.com' },
  ],
  airflow: [
    { label: 'Airflow GitHub',     url: 'https://github.com/apache/airflow' },
    { label: 'Good First Issues',  url: 'https://github.com/apache/airflow/issues?q=label%3A%22good+first+issue%22' },
    { label: 'Airflow Docs',       url: 'https://airflow.apache.org/docs/' },
    { label: 'Dev Mailing List',   url: 'https://lists.apache.org/list.html?dev@airflow.apache.org' },
    { label: 'Contributing Guide', url: 'https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst' },
  ],
}

export const DAY_LABELS: Record<string, { title: string; sub: string }> = {
  '1-2':   { title: 'Day 1–2',   sub: 'Setup & GitHub'      },
  '3-4':   { title: 'Day 3–4',   sub: 'Community Joining'   },
  '5-6':   { title: 'Day 5–6',   sub: 'First Contributions' },
  '7':     { title: 'Day 7',     sub: 'Feature PRs'         },
  '8':     { title: 'Day 8',     sub: 'Mentor Contact'       },
  '9-10':  { title: 'Day 9–10',  sub: 'Proposal Writing'    },
  '11':    { title: 'Day 11',    sub: 'Additional PRs'       },
  '12':    { title: 'Day 12',    sub: 'Proposal Polish'      },
  '13-14': { title: 'Day 13–14', sub: 'Final Submission'     },
}

export const DEFAULT_SPRINT_TASKS: { day: string; text: string }[] = [
  { day: '1-2', text: 'Update GitHub profile README with ML experience, tech stack, GSoC badge' },
  { day: '1-2', text: 'Pin best ML and research repositories on GitHub' },
  { day: '1-2', text: 'Add clear READMEs with architecture diagrams to pinned repos' },
  { day: '1-2', text: 'Study ML4SCI project list on GSoC page' },
  { day: '1-2', text: 'Study Kubeflow GSoC projects and select target' },
  { day: '1-2', text: 'Study Apache Airflow GSoC projects and select target' },
  { day: '1-2', text: 'Run ML4SCI/ML4DQM repository locally' },
  { day: '3-4', text: 'Join ML4SCI Slack channel and post intro message' },
  { day: '3-4', text: 'Join Kubeflow Slack / GitHub discussions' },
  { day: '3-4', text: 'Join Apache Airflow dev mailing list or Slack' },
  { day: '3-4', text: 'Find good-first-issue labels in all 3 orgs' },
  { day: '3-4', text: 'Submit PR #1 to ML4SCI (docs / README fix)' },
  { day: '5-6', text: 'Submit PR #2 to ML4SCI (bug fix with tests)' },
  { day: '5-6', text: 'Submit PR #1 to Kubeflow (docs or small fix)' },
  { day: '5-6', text: 'Read ML4DQM research paper and take notes' },
  { day: '5-6', text: 'Deep study dataset pipeline and model architecture' },
  { day: '7',   text: 'Submit PR #3 to ML4SCI (feature: metric module or data loader)' },
  { day: '7',   text: 'Submit PR #1 to Apache Airflow (good first issue)' },
  { day: '7',   text: 'Update sprint progress tracker' },
  { day: '8',   text: 'Send intro message to ML4SCI mentor via Slack' },
  { day: '8',   text: 'Send intro message to Kubeflow mentor' },
  { day: '8',   text: 'Log all mentor interactions in the Mentors tab' },
  { day: '8',   text: 'Submit PR #2 to Kubeflow (bug fix)' },
  { day: '9-10', text: 'Write proposal title, abstract, and problem statement' },
  { day: '9-10', text: 'Draw architecture diagram on Excalidraw (excalidraw.com)' },
  { day: '9-10', text: 'Complete 12-week timeline table' },
  { day: '9-10', text: 'Write deliverables and About Me sections' },
  { day: '11',  text: 'Submit PR #4 (performance opt or refactor — any org)' },
  { day: '11',  text: 'Grammar and clarity pass on proposal draft' },
  { day: '11',  text: 'Verify architecture diagram is clear and complete' },
  { day: '12',  text: 'Grammar, clarity, and technical depth review' },
  { day: '12',  text: 'Validate timeline is realistic' },
  { day: '12',  text: 'Confirm all links and diagrams work' },
  { day: '13-14', text: 'Send proposal draft to ML4SCI mentor for feedback' },
  { day: '13-14', text: 'Incorporate mentor feedback into proposal' },
  { day: '13-14', text: 'Submit PR #5 (final contribution)' },
  { day: '13-14', text: 'Submit final proposal on summerofcode.withgoogle.com' },
  { day: '13-14', text: 'Confirm submission confirmation email received' },
]