export const ORG_META: Record<string, { name: string; target: number; icon: string; color: string }> = {
  ml4sci:          { name: 'ML4SCI',          target: 3, icon: 'flask',  color: '#4ecdc4' },
  numfocus_pymc:   { name: 'NumFOCUS (PyMC)', target: 2, icon: 'cloud',  color: '#6fa3e0' },
  apache_fineract: { name: 'Apache Fineract', target: 1, icon: 'wind',   color: '#e8b86d' },
}

export const ORG_LINKS: Record<string, { label: string; url: string }[]> = {
  ml4sci: [
    { label: 'ML4SCI Org',                      url: 'https://github.com/ML4SCI' },
    { label: 'DeepLense Repo',                  url: 'https://github.com/ML4SCI/DeepLense' },
    { label: 'GSoC 2026 Ideas Page',            url: 'https://ml4sci.org/activities/gsoc2026.html' },
    { label: 'DEEPLENSE Project Page',          url: 'https://ml4sci.org/gsoc/projects/2026/project_DEEPLENSE.html' },
    { label: 'Diffusion Models Proposal',       url: 'https://ml4sci.org/gsoc/2026/proposal_DEEPLENSE8.html' },
    { label: 'Foundation Model Proposal',       url: 'https://ml4sci.org/gsoc/2026/proposal_DEEPLENSE4.html' },
    { label: 'Evaluation Test',                 url: 'https://docs.google.com/document/d/10APh49fvayGoSftzO4fGXs2HP3uvYSzG-fSrq4xHL1w/edit?usp=sharing' },
    { label: 'Submit Proposal (Google Form)',   url: 'https://forms.gle/SPXo8kSwHHptcBmk9' },
    { label: 'Contact Mentors',                 url: 'mailto:ml4-sci@cern.ch' },
    { label: 'CERN Open Data',                  url: 'https://opendata.cern.ch' },
  ],
  numfocus_pymc: [
    { label: 'PyMC GitHub Repo',                url: 'https://github.com/pymc-devs/pymc' },
    { label: 'PyTensor Repo',                   url: 'https://github.com/pymc-devs/pytensor' },
    { label: 'GSoC 2026 Projects Wiki',         url: 'https://github.com/pymc-devs/pymc/wiki/GSoC-2026-projects' },
    { label: 'How to Get Involved (Read First)', url: 'https://discourse.pymc.io/t/gsoc-2026-how-to-get-involved-with-pymc-please-read-before-posting/17622' },
    { label: 'PyMC Discourse (Community)',      url: 'https://discourse.pymc.io' },
    { label: 'Beginner Friendly Issues',        url: 'https://github.com/pymc-devs/pymc/issues?q=is%3Aopen+is%3Aissue+label%3A%22beginner+friendly%22' },
    { label: 'Contributing Guide',              url: 'https://www.pymc.io/projects/docs/en/latest/contributing/index.html' },
    { label: 'PyMC Examples Docs',              url: 'https://docs.pymc.io/projects/examples/en/latest/' },
    { label: 'NumFOCUS Org',                    url: 'https://github.com/numfocus' },
    { label: 'NumFOCUS Website',                url: 'https://numfocus.org' },
  ],
  apache_fineract: [
    { label: 'Fineract GitHub Repo',            url: 'https://github.com/apache/fineract' },
    { label: 'GSoC Program Wiki',               url: 'https://cwiki.apache.org/confluence/display/FINERACT/GSOC+Program+at+Fineract' },
    { label: 'GSoC 2026 — Self-Service API',    url: 'https://issues.apache.org/jira/browse/FINERACT-2439' },
    { label: 'GSoC 2026 — Frontend MVP POC',    url: 'https://issues.apache.org/jira/browse/FINERACT-2440' },
    { label: 'GSoC 2026 — Loan Origination',    url: 'https://issues.apache.org/jira/browse/FINERACT-2442' },
    { label: 'All Open Fineract Issues',        url: 'https://issues.apache.org/jira/projects/FINERACT/issues' },
    { label: 'Beginner Friendly Issues',        url: 'https://issues.apache.org/jira/browse/FINERACT-2489?filter=-1&jql=project%20%3D%20%22Apache%20Fineract%22%20and%20labels%20IN%20(beginner-friendly%2C%20beginner%2C%20begineer%2C%20beginners%2C%20Beginner)%20AND%20resolution%20%3D%20Unresolved%20order%20by%20created%20DESC' },
    { label: 'Dev Mailing List',                url: 'https://lists.apache.org/list.html?dev@fineract.apache.org' },
    { label: 'Fineract Documentation',          url: 'https://fineract.apache.org/docs/current/' },
    { label: 'Fineract FAQ (Confluence)',        url: 'https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=91554327' },
  ],
}

export const DAY_LABELS: Record<string, { title: string; sub: string }> = {
  '1-2':   { title: 'Day 1–2',   sub: 'Setup & GitHub'      },
  '3-4':   { title: 'Day 3–4',   sub: 'Community Joining'   },
  '5-6':   { title: 'Day 5–6',   sub: 'First Contributions' },
  '7':     { title: 'Day 7',     sub: 'Feature PRs'         },
  '8':     { title: 'Day 8',     sub: 'Mentor Contact'       },
  '9-10':  { title: 'Day 9–10',  sub: 'Proposal Writing'    },
  '11':    { title: 'Day 11',    sub: 'Additional PRs'       },
  '12':    { title: 'Day 12',    sub: 'Proposal Polish'      },
  '13-14': { title: 'Day 13–14', sub: 'Final Submission'     },
}

export const DEFAULT_SPRINT_TASKS: { day: string; text: string }[] = [
  { day: '1-2', text: 'Update GitHub profile README with ML experience, tech stack, GSoC badge' },
  { day: '1-2', text: 'Pin best ML and research repositories on GitHub' },
  { day: '1-2', text: 'Add clear READMEs with architecture diagrams to pinned repos' },
  { day: '1-2', text: 'Study ML4SCI DEEPLENSE project list on GSoC page' },
  { day: '1-2', text: 'Study NumFOCUS (PyMC) GSoC 2026 projects wiki and select target' },
  { day: '1-2', text: 'Study Apache Fineract GSoC 2026 Jira tickets and select target' },
  { day: '1-2', text: 'Clone and run ML4SCI/DeepLense repository locally' },
  { day: '3-4', text: 'Email ml4-sci@cern.ch with intro and research background' },
  { day: '3-4', text: 'Post intro on PyMC Discourse and engage with community' },
  { day: '3-4', text: 'Join Apache Fineract dev mailing list and post intro' },
  { day: '3-4', text: 'Find beginner-friendly issues in all 3 orgs' },
  { day: '3-4', text: 'Submit PR #1 to ML4SCI DeepLense (docs / README fix)' },
  { day: '5-6', text: 'Submit PR #2 to ML4SCI DeepLense (bug fix with tests)' },
  { day: '5-6', text: 'Submit PR #1 to PyMC or PyTensor (beginner friendly issue)' },
  { day: '5-6', text: 'Read DEEPLENSE diffusion model paper and take notes' },
  { day: '5-6', text: 'Complete ML4SCI evaluation test (DEEPLENSE8 / DEEPLENSE4)' },
  { day: '7',   text: 'Submit PR #3 to ML4SCI DeepLense (feature or model improvement)' },
  { day: '7',   text: 'Submit PR #1 to Apache Fineract (beginner Jira ticket)' },
  { day: '7',   text: 'Update sprint progress tracker' },
  { day: '8',   text: 'Send intro + eval test to ML4SCI via ml4-sci@cern.ch' },
  { day: '8',   text: 'Send intro message to PyMC mentor on Discourse' },
  { day: '8',   text: 'Log all mentor interactions in the Mentors tab' },
  { day: '8',   text: 'Submit PR #2 to PyMC (bug fix or doc improvement)' },
  { day: '9-10', text: 'Write proposal title, abstract, and problem statement' },
  { day: '9-10', text: 'Draw architecture diagram on Excalidraw (excalidraw.com)' },
  { day: '9-10', text: 'Complete 12-week timeline table' },
  { day: '9-10', text: 'Write deliverables and About Me sections — mention publications' },
  { day: '11',  text: 'Submit PR #4 (performance opt or refactor — any org)' },
  { day: '11',  text: 'Grammar and clarity pass on proposal draft' },
  { day: '11',  text: 'Verify architecture diagram is clear and complete' },
  { day: '12',  text: 'Grammar, clarity, and technical depth review' },
  { day: '12',  text: 'Validate timeline is realistic' },
  { day: '12',  text: 'Confirm all links and diagrams work' },
  { day: '13-14', text: 'Send proposal draft to ML4SCI mentor for feedback' },
  { day: '13-14', text: 'Incorporate mentor feedback into proposal' },
  { day: '13-14', text: 'Submit PR #5 (final contribution)' },
  { day: '13-14', text: 'Submit final proposal on summerofcode.withgoogle.com' },
  { day: '13-14', text: 'Confirm submission confirmation email received' },
]